### ISSUE TITLE
build on Macosx 10.11 error

### ISSUE THREAD

**Issue by M0REKZ** [WohlSoft/PGE-Project#357]
my username is replaced by "USRNAME"

```
.......................
[ 36%] Built target pge_editor_autogen
[ 36%] Building CXX object Engine/CMakeFiles/pge_engine.dir/fontman/ttf_font.cpp.o
Scanning dependencies of target pge_calibrator_autogen
[ 36%] Automatic MOC for target pge_calibrator
/Users/USRNAME/lab/test/hx2/PGE-Project/Engine/fontman/ttf_font.cpp:54:34: error: 
      default initialization of an object of const type
      'const TtfFont::TheGlyph' without a user-provided default constructor
const TtfFont::TheGlyph TtfFont::dummyGlyph;
                                 ^
                                           {}
1 error generated.
make[2]: *** [Engine/CMakeFiles/pge_engine.dir/fontman/ttf_font.cpp.o] Error 1
make[1]: *** [Engine/CMakeFiles/pge_engine.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 36%] Built target pge_calibrator_autogen
make: *** [all] Error 2
=======================AN ERROR OCCURRED!=======================
```

macosx 10.11 with xcode 8.2.1 and Qt 5.11.3 (with QMake 3.1)

i run "build.sh" on "PGE-Project" directory

**Comment by Wohlstand** [comment]
looks odd... I bet it's a small fix...

**Comment by Wohlstand** [comment]
Just now I sent a minor commit, can you try to pull and build it now?

**Comment by M0REKZ** [comment]
now i builded it... but is for Macos 10.12...

**Comment by M0REKZ** [comment]
What file and line i need to modify?

**Comment by Wohlstand** [comment]
You need to modify this file:
Engine/fontman/ttf_font.cpp:54

look the change here: https://github.com/WohlSoft/PGE-Project/commit/6b4e79bba27308d7a29671a82143a8ff9d0c4b2d

**Comment by M0REKZ** [comment]
i builded it, I was referring to a cmake line for change macos version
